credentials:
  usernames:
    sanju:
      email: abhishekmj5560@gmail.com
      name: abhi
      password: hi
    jim:
      email: jim@gmail.com
      name:  abhishek
      password: hi
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
# preauthorized:
#   emails:
#   - melsby@gmail.com